=== Saber2pr/profile-generator/data.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "margin": {
      "type": "string"
    },
    "profile": {
      "type": "object",
      "properties": {
        "imgSrc": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "target": {
          "type": "string"
        },
        "birth": {
          "type": "string"
        },
        "location": {
          "type": "string"
        },
        "school": {
          "type": "string"
        },
        "mobile": {
          "type": "string"
        },
        "mail": {
          "type": "string"
        },
        "workLinks": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string"
              },
              "href": {
                "type": "string"
              }
            }
          }
        },
        "socialLinks": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string"
              },
              "href": {
                "type": "string"
              }
            }
          }
        }
      }
    },
    "opensource": {
      "type": "object",
      "properties": {
        "title": {
          "type": "string"
        },
        "works": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string"
              },
              "href": {
                "type": "string"
              },
              "describes": {
                "type": "array",
                "items": {
                  "type": "object",
                  "properties": {
                    "content": {
                      "type": "string"
                    },
                    "keywords": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "word": {
                            "type": "string"
                          },
                          "style": {
                            "type": "string"
                          }
                        },
                        "required": ["word", "style"]
                      }
                    }
                  },
                  "required": ["content"]
                }
              }
            },
            "required": ["name", "describes"]
          }
        }
      }
    },
    "worksexp": {
      "type": "object",
      "properties": {
        "title": {
          "type": "string"
        },
        "works": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string"
              },
              "href": {
                "type": "string"
              },
              "describes": {
                "type": "array",
                "items": {
                  "type": "object",
                  "properties": {
                    "content": {
                      "type": "string"
                    },
                    "keywords": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "word": {
                            "type": "string"
                          },
                          "style": {
                            "type": "string"
                          }
                        },
                        "required": ["word", "style"]
                      }
                    }
                  },
                  "required": ["content"]
                }
              }
            },
            "required": ["name", "describes"]
          }
        }
      }
    },
    "ability": {
      "type": "object",
      "properties": {
        "title": {
          "type": "string"
        },
        "items": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "type": {
                "type": "string"
              },
              "describes": {
                "type": "array",
                "items": {
                  "type": "object",
                  "properties": {
                    "content": {
                      "type": "string"
                    },
                    "keywords": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "word": {
                            "type": "string"
                          },
                          "style": {
                            "type": "string"
                          }
                        }
                      }
                    }
                  },
                  "required": ["content"]
                }
              }
            },
            "required": ["type", "describes"]
          }
        }
      }
    },
    "rate": {
      "type": "object",
      "properties": {
        "title": {
          "type": "string"
        },
        "describes": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "content": {
                "type": "string"
              }
            },
            "required": ["content"]
          }
        }
      }
    }
  }
}

=== Saber2pr/profile-generator/data.json
{
  "profile": {
    "imgSrc": "https://bkimg.cdn.bcebos.com/pic/21a4462309f7905243d5124f0ef3d7ca7acbd5fd?x-bce-process=image/watermark,g_7,image_d2F0ZXIvYmFpa2U4MA==,xp_5,yp_5",
    "name": "妖梦",
    "target": "庭师",
    "birth": "??-??-??",
    "location": "白玉楼",
    "school": "冥界-白玉楼",
    "mobile": "sdfdsfhdfg",
    "mail": "youmu@konpaku.com",
    "workLinks": [
      {
        "name": "Github",
        "href": "https://github.com/Saber2pr"
      }
    ],
    "socialLinks": [
      {
        "name": "个人博客",
        "href": "https://saber2pr.top"
      }
    ]
  },
  "opensource": {
    "title": "武器",
    "works": [
      {
        "name": "楼观剑",
        "href": "#saber1",
        "describes": [
          {
            "content": "据传楼观剑是妖怪锻造的，太长不适合人类用。一挥有杀伤十只幽灵的威力。不过幽灵是无法杀伤的（×4幽灵通常是成佛，或者消灭。），无法判断到底有多少成分是真实的（×5据说斩不断的东西几乎不存在。）",
            "keywords": [
              {
                "word": "斩不断的东西几乎不存在",
                "style": "color:#3e92a9;text-decoration:underline;font-style:italic;"
              }
            ]
          }
        ]
      }
    ]
  },
  "worksexp": {
    "title": "技能",
    "works": [
      {
        "name": "白楼剑",
        "href": "#saber2",
        "describes": [
          {
            "content": "是魂魄家的家传宝刀，据说能斩断对象的迷惘。对幽灵使用会成佛，对人类使用则是很难受并且会痛的。而且能用此刀的只有魂魄家的人，原因不明。",
            "keywords": [
              {
                "word": "人类",
                "style": "color:#3e92a9;text-decoration:underline;font-style:italic;"
              }
            ]
          }
        ]
      }
    ]
  },
  "ability": {
    "title": "设定文档",
    "items": [
      {
        "type": "日常",
        "describes": [
          {
            "content": "早上比主人早起，巡视庭园。白天修剪庭园和修行剑术，有事务就出门。夜晚再巡视一遍，在白玉楼的主人就寝后才去睡觉"
          }
        ]
      },
      {
        "type": "目击者报告",
        "describes": [
          {
            "content": "去冥界玩时，她总是先斩了再说。我希望她能看清对方是谁再动手。（博丽灵梦）还活着的人过去冥界玩，这该说什么好呢。",
            "keywords": [
              {
                "word": "先斩了再说",
                "style": "color:#a9368b;text-decoration:underline;font-style:italic;"
              }
            ]
          },
          {
            "content": "她常来光顾购物，但我总觉得她是来接我过去的，心情变差了。（匿名）她只是来购物的，就放轻松一些吧……"
          }
        ]
      }
    ]
  },
  "rate": {
    "title": "???",
    "describes": [
      {
        "content": "魂魄妖梦（こんぱく ようむ，Youmu Konpaku）是系列作品《东方project》中的虚拟角色，住在位于冥界的白玉楼，于《东方妖妖梦》首次登场。"
      }
    ]
  }
}
